version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_inventory
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev # Указываем на файл для разработки
    container_name: inventory_app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - .:/app # КРИТИЧНО: связывает твой код на диске с контейнером
    depends_on:
      - mongodb
    tty: true
    stdin_open: true

volumes:
  mongo_data:
